import { deckUrl, renewal } from '../../data/renewalData.js';

const PLACEHOLDER_SLIDES = Array.from({ length: 6 });

export default function ProposalDeckTab() {
  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div>
          <h2
            className="text-[22px] font-semibold tracking-[-0.01em]"
            style={{ fontFamily: 'var(--font-serif)', color: 'var(--text-strong)' }}
          >
            Proposal Deck
          </h2>
          <p
            className="text-[11px] mt-0.5"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-subtle)' }}
          >
            Generated by Proposal Agent · Stage 3 of 4
          </p>
        </div>
        <span
          className="text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-full"
          style={{ fontFamily: 'var(--font-mono)', background: 'var(--clay-100)', color: 'var(--clay-700)' }}
        >
          Proposal Agent
        </span>
      </div>

      {/* Content */}
      {deckUrl ? (
        <iframe
          src={deckUrl}
          style={{ width: '100%', height: 'calc(100vh - 200px)', border: 'none', borderRadius: 12 }}
          allowFullScreen
          title="Proposal Deck"
        />
      ) : (
        <div
          className="rounded-xl p-8"
          style={{
            background: 'var(--surface-card)',
            border: '1px solid var(--border-default)',
            boxShadow: 'var(--shadow-sm)',
          }}
        >
          <div className="grid grid-cols-3 gap-4 mb-6">
            {PLACEHOLDER_SLIDES.map((_, i) => (
              <div
                key={i}
                className="rounded-lg flex items-center justify-center"
                style={{
                  aspectRatio: '16/9',
                  background: i === 0 ? 'var(--clay-100)' : 'var(--surface-sunken)',
                  border: '1px solid var(--border-default)',
                }}
              >
                {i === 0 && (
                  <p
                    className="text-[13px] text-center leading-snug px-3"
                    style={{ fontFamily: 'var(--font-serif)', color: 'var(--clay-600)' }}
                  >
                    {renewal.vendor} × {renewal.buyerCompany}<br />Renewal Proposal
                  </p>
                )}
              </div>
            ))}
          </div>
          <p
            className="text-[11px] text-center"
            style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-subtle)' }}
          >
            The proposal deck will appear here automatically once generated by the Proposal Agent.
          </p>
        </div>
      )}
    </div>
  );
}
